default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: todo
  username: todo
  password: todo
  host: localhost

test:
  <<: *default
  database: todo_test
  username: todo
  password: todo
  host: localhost

production:
  <<: *default
  database: rails-rest-api_production
  username: rails-rest-api
  password: <%= ENV['RAILS-REST-API_DATABASE_PASSWORD'] %>
